name: Deploy

on:
  push:
    branches:
    - master

jobs:
  deploy_lambda:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - with:
        node-version: '12'
      - name: npm install
        env:
          CI: true
        run:
          npm ci
      - name: deploy
        run: |
        # convert ts to js
          npx ncc build index.ts
        # zip up js file
          zip -j deploy.zip ./dist/*
        # deploy code through cli
          aws lambda update-function-code --function-name=lambda-gh-action --zip-file=fileb://deploy.zip
        # add aws credentials